export enum Day {
  Sunday = 'SUN',
  Monday = 'MN',
  Tuesday = "TUE",
  Thursday = 'THU',
  Saturday = 'SN'
}

export enum Conditions {
  Cold = 'Cold',
  ClosedRoof = 'Closed Roof',
  Dome = 'Dome',
  Flurries = 'Flurries',
  LightSnow = 'Light Snow',
  Snow = 'Snow',
  ChanceRain = 'Chance Rain',
  LightRain = 'Light Rain',
  Rain = 'Rain',
  MostlyCloudy = 'Mostly Cloudy',
  PartlyCloudy = 'Partly Cloudy',
  Cloudy = 'Cloudy',
  MostlySunny = 'Mostly Sunny',
  PartlySunny = 'Partly Sunny',
  Sunny = 'Sunny',
  Hazy = 'Hazy',
  Foggy = 'Foggy',
  Clear = 'Clear',
  Fair = 'Fair'
}

export enum Surface {
  Grass = 'Grass',
  AstroTurf = 'AstroTurf',
  AstroPlay = 'AstroPlay',
  FieldTurf = 'FieldTurf',
  SportGrass = 'SportGrass',
  NeXTurf = 'NeXTurf',
  MomentumTurf = 'MomentumTurf',
  DDGrassMaster = 'DD GrassMaster',
  Sportex = 'Sportex',
  ATurfTitan = 'A Turf Titan',
  UBUSpeedSeriesS5M = 'UBU Speed Series S5M'
}

export enum TeamName {
  ArizonaCardinals = 'ARI',
  AtlantaFalcons = 'ATL',
  BaltimoreRavens = 'BAL',
  BuffaloBills = 'BUF',
  CarolinaPanthers = 'CAR',
  ChicagoBears = 'CHI',
  CincinnatiBengals = 'CIN',
  ClevelandBrowns = 'CLE',
  DallasCowboys = 'DAL',
  DenverBroncos = 'DEN',
  DetroitLions = 'DET',
  GreenBayPackers = 'GB',
  HoustonTexans = 'HOU',
  IndianapolisColts = 'IND',
  JacksonvilleJaguars = 'JAC',
  KansasCityChiefs = 'KC',
  LosAngelesRams = 'LA',
  LosAngelesChargers = 'LAC',
  LasVegasRaiders = 'LV',
  MiamiDolphins = 'MIA',
  MinnesotaVikings = 'MIN',
  NewEnglandPatriots = 'NE',
  NewOrleansSaints = 'NO',
  NewYorkGiants = 'NYG',
  NewYorkJets = 'NYJ',
  OaklandRaiders = 'OAK',
  PhiladelphiaEagles = 'PHI',
  PittsburghSteelers = 'PIT',
  SanDiegoChargers = 'SD',
  SeattleSeahawks = 'SEA',
  SanFrancisco49ers = 'SF',
  StLouisRams = 'STL',
  TampaBayBuccaneers = 'TB',
  TennesseeTitans = 'TEN',
  WashingtonRedskins = 'WAS'
}