import { Game } from "./GameTypes";
import { BettingOdds } from "./BettingOddsTypes";
import { TeamName, Day } from "./ModelConstantTypes";

export type SchedulePrediction = {
  scheduleId: string,
  gameId: string,
  game?: Game,
  bettingOdds?: BettingOdds,
  seasonYear: number,
  weekNumber: number,
  dayOfWeek: Day,
  date: string,
  visitingTeamName: TeamName,
  visitingTeamEloRating: number,
  visitingTeamEloRatingRank: number,
  visitingTeamEloWinExp: number,
  homeTeamName: TeamName,
  homeTeamEloRating: number,
  homeTeamEloRatingRank: number,
  homeTeamEloWinExp: number,
  // Head-to-head Fields
  // Home
  homePointsScoredAmtAvg: number,
  homePointsScoredAmt: number,
  homePointsScoredRank: number,
  homePointsAllowedAmtAvg: number,
  homePointsAllowedAmt: number,
  homePointsAllowedRank: number,
  homeRushingFirstDownsAmt: number,
  homeRushingFirstDownsRank: number,
  homeRushingFirstDownsAllowedAmt: number,
  homeRushingFirstDownsAllowedRank: number,
  homePassingFirstDownsAmt: number,
  homePassingFirstDownsRank: number,
  homePassingFirstDownsAllowedAmt: number,
  homePassingFirstDownsAllowedRank: number,
  homeRushingYardsAmtAvg: number,
  homeRushingYardsAmt: number,
  homeRushingYardsRank: number,
  homeRushingYardsAllowedAmt: number,
	homeRushingYardsAllowedRank: number,
  homeRushingAttemptsAmt: number,
  homeRushingAttemptsRank: number,
  homeRushingAttemptsAllowedAmt: number,
	homeRushingAttemptsAllowedRank: number,
  homePassingYardsAmtAvg: number,
  homePassingYardsAmt: number,
  homePassingYardsRank: number,
  homePassingYardsAllowedAmt: number,
	homePassingYardsAllowedRank: number,
  homePassingAttemptsAmt: number,
  homePassingAttemptsRank: number,
  homePassingAttemptsAllowedAmt: number,
  homePassingAttemptsAllowedRank: number,
  // Visitor
  visitingPointsScoredAmtAvg: number,
  visitingPointsScoredAmt: number,
  visitingPointsScoredRank: number,
  visitingPointsAllowedAmtAvg: number,
  visitingPointsAllowedAmt: number,
  visitingPointsAllowedRank: number,
  visitingRushingFirstDownsAmt: number,
  visitingRushingFirstDownsRank: number,
  visitingRushingFirstDownsAllowedAmt: number,
  visitingRushingFirstDownsAllowedRank: number,
  visitingPassingFirstDownsAmt: number,
  visitingPassingFirstDownsRank: number,
  visitingPassingFirstDownsAllowedAmt: number,
  visitingPassingFirstDownsAllowedRank: number,
  visitingRushingYardsAmtAvg: number,
  visitingRushingYardsAmt: number,
  visitingRushingYardsRank: number,
  visitingRushingYardsAllowedAmt: number,
	visitingRushingYardsAllowedRank: number,
  visitingRushingAttemptsAmt: number,
  visitingRushingAttemptsRank: number,
  visitingRushingAttemptsAllowedAmt: number,
	visitingRushingAttemptsAllowedRank: number,
  visitingPassingYardsAmtAvg: number,
  visitingPassingYardsAmt: number,
  visitingPassingYardsRank: number,
  visitingPassingYardsAllowedAmt: number,
	visitingPassingYardsAllowedRank: number,
  visitingPassingAttemptsAmt: number,
  visitingPassingAttemptsRank: number,
  visitingPassingAttemptsAllowedAmt: number,
  visitingPassingAttemptsAllowedRank: number,
}

export type SchedulePredictionsAccuracy = {
  predictionsAmt: number,
  correctPredictionsAmt: number,
  predictionsGuessRate: number,
  confidentPredictionsAmt: number,
  correctConfidentPredictionsAmt: number,
  confidentPredictionsGuessRate: number,
  againstTheSpreadPredictionsAmt: number,
  correctAgainstTheSpreadPredictionsAmt: number,
  againstTheSpreadPredictionsGuessRate: number
}